import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import fs from 'fs-extra';
import { format } from 'prettier';
import * as helper from './helper.js';

const DIR_SRC = helper.resolve(/* SVG Director */'node_modules/@element-plus/icons-svg');
const DIR_DEST = helper.resolve('src/components/icons');

export async function run() {
  const pkgPath = path.join(DIR_SRC, 'package.json');
  if (!fs.existsSync(pkgPath)) {
    throw new Error(`⚠️ "${ pkgPath }" not found.`);
  }

  const { version: currentVersion } = fs.readJsonSync(pkgPath);

  // 优先确保目标文件夹存在
  fs.ensureDirSync(DIR_DEST);

  const cachePath = path.join(DIR_DEST, '.icon-version.json');
  if (fs.existsSync(cachePath)) {
    const { version: localVersion } = fs.readJsonSync(cachePath);
    if (localVersion === currentVersion) {
      return 'Skip';
    }
  }

  const fileNames = helper.globSync(DIR_SRC, 'file')
    .filter(name => name.endsWith('.svg'))
    .map(name => name.replace('.svg', ''));

  const indexTSTemplate = `
// Auto-Generated by scripts/gen-icon.js
// DON'T EDIT THIS!!!

$exports
`.trimStart();
  const indexTSExports = fileNames
    .map(name => `export { default as ${ helper.pascal(name) } } from './${ name }.vue';`)
    .join('\n');
  const indexTSContent = indexTSTemplate.replace('$exports', indexTSExports);

  // 写入之前清空目标文件夹
  fs.emptyDirSync(DIR_DEST);

  // 写入 index.ts
  fs.writeFileSync(path.join(DIR_DEST, 'index.ts'), indexTSContent, 'utf8');
  // 写入 <component-name>.vue
  fileNames.forEach(async (name) => {
    const dest = path.join(DIR_DEST, `${ name }.vue`);
    if (fs.existsSync(dest)) return;

    const raw = await fs.readFile(path.join(DIR_SRC, `${ name }.svg`), 'utf8');
    const content = raw
      .replace('xml:space="preserve"', '')
      .replace('<svg', `<svg data-name="${ name }" width="1em" height="1em" fill="currentColor" focusable="false"`);

    const code = await format(`<template functional>${ content }</template>`, { parser: 'vue' });
    await fs.writeFile(dest, code, 'utf8');
  });

  // 写入当前版本，供下次校验
  fs.writeJsonSync(cachePath, { version: currentVersion });
}

if (import.meta && import.meta.url) {
  const realpath = fs.realpathSync(fileURLToPath(import.meta.url));
  const isMain = realpath === fs.realpathSync(process.argv[1]);
  isMain && run()
    .then((log) => {
      console.log(`✨ Done${ log ? `(${ log })` : '' }.`);
    })
    .catch(console.error);
}
