// Auto-Generated by scripts/gen-ui.js
// Date: 2026/8/26 21:51:31
// DON'T EDIT THIS!!!

import type { DefineComponent, PluginFunction, VueConstructor } from 'vue';

// Components
import { Button } from './button';
import { Checkbox, CheckboxGroup } from './checkbox';
import { FocusTrap } from './focus-trap';
import { Form } from './form';
import { Input } from './input';
import { Flex } from './layout';
import { Popper } from './popper';
import { Radio, RadioGroup } from './radio';
import { Scrollbar } from './scrollbar';
import { OnlyChild } from './slot';
import { Teleport, RenderApp } from './teleport';
import { Tooltip } from './tooltip';
import { Tree } from './tree';

// Plugins
// no import-plugins

const components = {
  ElButton: Button,
  ElCheckbox: Checkbox,
  ElCheckboxGroup: CheckboxGroup,
  ElFocusTrap: FocusTrap,
  ElForm: Form,
  ElInput: Input,
  ElFlex: Flex,
  ElPopper: Popper,
  ElRadio: Radio,
  ElRadioGroup: RadioGroup,
  ElScrollbar: Scrollbar,
  ElOnlyChild: OnlyChild,
  ElTeleport: Teleport,
  ElRenderApp: RenderApp,
  ElTooltip: Tooltip,
  ElTree: Tree,
} as unknown as Record<string, DefineComponent>;

const plugins = [
// no plugins
] as PluginFunction<any>[];

export * from './button';
export * from './checkbox';
export * from './focus-trap';
export * from './form';
export * from './input';
export * from './layout';
export * from './popper';
export * from './radio';
export * from './scrollbar';
export * from './slot';
export * from './teleport';
export * from './tooltip';
export * from './tree';

let isInstalled = false;
export default function install(Vue: VueConstructor) {
  if (isInstalled) return;
  isInstalled = true;

  Object.entries(components).forEach(([n, c]) => Vue.component(n, c));
  plugins.forEach(p => Vue.use(p));
}
