// Auto-Generated by scripts/gen-ui.js
// Date: 2026/6/15 19:15:29
// DON'T EDIT THIS!!!

import type { DefineComponent, PluginFunction, VueConstructor } from 'vue';

// Components
import { Button } from './button';
import { Checkbox, CheckboxGroup } from './checkbox';
import { FocusTrap } from './focus-trap';
import { Form } from './form';
import { Icon } from './icon';
import { Flex } from './layout';
import { Popper } from './popper';
import { Radio, RadioGroup } from './radio';
import { Scrollbar } from './scrollbar';
import { OnlyChild } from './slot';
import { Teleport, RenderApp } from './teleport';
import { Tooltip } from './tooltip';

// Plugins
// no import-plugins

const components = {
  ElButton: Button,
  ElCheckbox: Checkbox,
  ElCheckboxGroup: CheckboxGroup,
  ElFocusTrap: FocusTrap,
  ElForm: Form,
  ElIcon: Icon,
  ElFlex: Flex,
  ElPopper: Popper,
  ElRadio: Radio,
  ElRadioGroup: RadioGroup,
  ElScrollbar: Scrollbar,
  ElOnlyChild: OnlyChild,
  ElTeleport: Teleport,
  ElRenderApp: RenderApp,
  ElTooltip: Tooltip,
} as unknown as Record<string, DefineComponent>;

const plugins = [
// no plugins
] as PluginFunction<any>[];

export * from './button';
export * from './checkbox';
export * from './focus-trap';
export * from './form';
export * from './icon';
export * from './layout';
export * from './popper';
export * from './radio';
export * from './scrollbar';
export * from './slot';
export * from './teleport';
export * from './tooltip';

let isInstalled = false;
export default function install(Vue: VueConstructor) {
  if (isInstalled) return;
  isInstalled = true;

  Object.entries(components).forEach(([n, c]) => Vue.component(n, c));
  plugins.forEach(p => Vue.use(p));
}
