// Auto-Generated by scripts/gen-ui.js
// Date: 2025/6/22 14:28:07
// DON'T EDIT THIS!!!

import type { DefineComponent, PluginFunction, VueConstructor } from 'vue';

// Components
import { Button } from './button';
import { Checkbox, CheckboxGroup } from './checkbox';
import { Flex } from './layout';
import { Radio, RadioGroup } from './radio';
import { Teleport } from './teleport';

// Plugins
// no import-plugins

const components = {
  ElButton: Button,
  ElCheckbox: Checkbox,
  ElCheckboxGroup: CheckboxGroup,
  ElFlex: Flex,
  ElRadio: Radio,
  ElRadioGroup: RadioGroup,
  ElTeleport: Teleport,
} as unknown as Record<string, DefineComponent>;

const plugins = [
// no plugins
] as PluginFunction<any>[];

export * from './button';
export * from './checkbox';
export * from './layout';
export * from './radio';
export * from './teleport';

let isInstalled = false;
export default function install(Vue: VueConstructor) {
  if (isInstalled) return;
  isInstalled = true;

  Object.entries(components).forEach(([n, c]) => Vue.component(n, c));
  plugins.forEach(p => Vue.use(p));
}
