// Auto-Generated by scripts/gen-ui.js
// Date: 2026/8/31 23:00:41
// DON'T EDIT THIS!!!

export {};

// Read more: https://github.com/vuejs/core/pull/3399
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('./button')['Button'];
    ElCheckbox: typeof import('./checkbox')['Checkbox'];
    ElCheckboxGroup: typeof import('./checkbox')['CheckboxGroup'];
    ElFocusTrap: typeof import('./focus-trap')['FocusTrap'];
    ElForm: typeof import('./form')['Form'];
    ElIcon: typeof import('./icon')['Icon'];
    ElInput: typeof import('./input')['Input'];
    ElFlex: typeof import('./layout')['Flex'];
    ElPopper: typeof import('./popper')['Popper'];
    ElRadio: typeof import('./radio')['Radio'];
    ElRadioGroup: typeof import('./radio')['RadioGroup'];
    ElScrollbar: typeof import('./scrollbar')['Scrollbar'];
    ElOnlyChild: typeof import('./slot')['OnlyChild'];
    ElSwitch: typeof import('./switch')['Switch'];
    ElTag: typeof import('./tag')['Tag'];
    ElCheckTag: typeof import('./tag')['CheckTag'];
    ElTeleport: typeof import('./teleport')['Teleport'];
    ElRenderApp: typeof import('./teleport')['RenderApp'];
    ElTooltip: typeof import('./tooltip')['Tooltip'];
    ElTree: typeof import('./tree')['Tree'];
    ['el-button']: typeof import('./button')['Button'];
    ['el-checkbox']: typeof import('./checkbox')['Checkbox'];
    ['el-checkbox-group']: typeof import('./checkbox')['CheckboxGroup'];
    ['el-focus-trap']: typeof import('./focus-trap')['FocusTrap'];
    ['el-form']: typeof import('./form')['Form'];
    ['el-icon']: typeof import('./icon')['Icon'];
    ['el-input']: typeof import('./input')['Input'];
    ['el-flex']: typeof import('./layout')['Flex'];
    ['el-popper']: typeof import('./popper')['Popper'];
    ['el-radio']: typeof import('./radio')['Radio'];
    ['el-radio-group']: typeof import('./radio')['RadioGroup'];
    ['el-scrollbar']: typeof import('./scrollbar')['Scrollbar'];
    ['el-only-child']: typeof import('./slot')['OnlyChild'];
    ['el-switch']: typeof import('./switch')['Switch'];
    ['el-tag']: typeof import('./tag')['Tag'];
    ['el-check-tag']: typeof import('./tag')['CheckTag'];
    ['el-teleport']: typeof import('./teleport')['Teleport'];
    ['el-render-app']: typeof import('./teleport')['RenderApp'];
    ['el-tooltip']: typeof import('./tooltip')['Tooltip'];
    ['el-tree']: typeof import('./tree')['Tree'];
  }

  interface ComponentCustomProperties {

  }
}
